export const countryOptionsEN = [
  { value: 'af', label: 'Afghanistan' },
  { value: 'al', label: 'Albania' },
  { value: 'dz', label: 'Algeria' },
  { value: 'ad', label: 'Andorra' },
  { value: 'ao', label: 'Angola' },
  { value: 'ag', label: 'Antigua and Barbuda' },
  { value: 'ar', label: 'Argentina' },
  { value: 'am', label: 'Armenia' },
  { value: 'au', label: 'Australia' },
  { value: 'at', label: 'Austria' },
  { value: 'az', label: 'Azerbaijan' },
  { value: 'bs', label: 'Bahamas' },
  { value: 'bh', label: 'Bahrain' },
  { value: 'bd', label: 'Bangladesh' },
  { value: 'bb', label: 'Barbados' },
  { value: 'by', label: 'Belarus' },
  { value: 'be', label: 'Belgium' },
  { value: 'bz', label: 'Belize' },
  { value: 'bj', label: 'Benin' },
  { value: 'bt', label: 'Bhutan' },
  { value: 'bo', label: 'Bolivia' },
  { value: 'ba', label: 'Bosnia and Herzegovina' },
  { value: 'bw', label: 'Botswana' },
  { value: 'br', label: 'Brazil' },
  { value: 'bn', label: 'Brunei' },
  { value: 'bg', label: 'Bulgaria' },
  { value: 'bf', label: 'Burkina Faso' },
  { value: 'bi', label: 'Burundi' },
  { value: 'kh', label: 'Cambodia' },
  { value: 'cm', label: 'Cameroon' },
  { value: 'ca', label: 'Canada' },
  { value: 'cv', label: 'Cape Verde' },
  { value: 'cf', label: 'Central African Republic' },
  { value: 'td', label: 'Chad' },
  { value: 'cl', label: 'Chile' },
  { value: 'cn', label: 'China' },
  { value: 'co', label: 'Colombia' },
  { value: 'km', label: 'Comoros' },
  { value: 'cg', label: 'Congo' },
  { value: 'cr', label: 'Costa Rica' },
  { value: 'hr', label: 'Croatia' },
  { value: 'cu', label: 'Cuba' },
  { value: 'cy', label: 'Cyprus' },
  { value: 'cz', label: 'Czechia' },
  { value: 'cd', label: 'Democratic Republic of the Congo' },
  { value: 'dk', label: 'Denmark' },
  { value: 'dj', label: 'Djibouti' },
  { value: 'dm', label: 'Dominica' },
  { value: 'do', label: 'Dominican Republic' },
  { value: 'tl', label: 'East Timor' },
  { value: 'ec', label: 'Ecuador' },
  { value: 'eg', label: 'Egypt' },
  { value: 'sv', label: 'El Salvador' },
  { value: 'gq', label: 'Equatorial Guinea' },
  { value: 'er', label: 'Eritrea' },
  { value: 'ee', label: 'Estonia' },
  { value: 'et', label: 'Ethiopia' },
  { value: 'fj', label: 'Fiji' },
  { value: 'fi', label: 'Finland' },
  { value: 'fr', label: 'France' },
  { value: 'ga', label: 'Gabon' },
  { value: 'gm', label: 'Gambia' },
  { value: 'ge', label: 'Georgia' },
  { value: 'de', label: 'Germany' },
  { value: 'gh', label: 'Ghana' },
  { value: 'gr', label: 'Greece' },
  { value: 'gd', label: 'Grenada' },
  { value: 'gt', label: 'Guatemala' },
  { value: 'gn', label: 'Guinea' },
  { value: 'gw', label: 'Guinea-Bissau' },
  { value: 'gy', label: 'Guyana' },
  { value: 'ht', label: 'Haiti' },
  { value: 'hn', label: 'Honduras' },
  { value: 'hu', label: 'Hungary' },
  { value: 'is', label: 'Iceland' },
  { value: 'in', label: 'India' },
  { value: 'id', label: 'Indonesia' },
  { value: 'ir', label: 'Iran' },
  { value: 'iq', label: 'Iraq' },
  { value: 'ie', label: 'Ireland' },
  { value: 'il', label: 'Israel' },
  { value: 'it', label: 'Italy' },
  { value: 'ci', label: 'Ivory Coast' },
  { value: 'jm', label: 'Jamaica' },
  { value: 'jp', label: 'Japan' },
  { value: 'jo', label: 'Jordan' },
  { value: 'kz', label: 'Kazakhstan' },
  { value: 'ke', label: 'Kenya' },
  { value: 'ki', label: 'Kiribati' },
  { value: 'kp', label: 'North Korea' },
  { value: 'kr', label: 'South Korea' },
  { value: 'kw', label: 'Kuwait' },
  { value: 'kg', label: 'Kyrgyzstan' },
  { value: 'la', label: 'Laos' },
  { value: 'lv', label: 'Latvia' },
  { value: 'lb', label: 'Lebanon' },
  { value: 'ls', label: 'Lesotho' },
  { value: 'lr', label: 'Liberia' },
  { value: 'ly', label: 'Libya' },
  { value: 'li', label: 'Liechtenstein' },
  { value: 'lt', label: 'Lithuania' },
  { value: 'lu', label: 'Luxembourg' },
  { value: 'mk', label: 'North Macedonia' },
  { value: 'mg', label: 'Madagascar' },
  { value: 'mw', label: 'Malawi' },
  { value: 'my', label: 'Malaysia' },
  { value: 'mv', label: 'Maldives' },
  { value: 'ml', label: 'Mali' },
  { value: 'mt', label: 'Malta' },
  { value: 'mh', label: 'Marshall Islands' },
  { value: 'mr', label: 'Mauritania' },
  { value: 'mu', label: 'Mauritius' },
  { value: 'mx', label: 'Mexico' },
  { value: 'fm', label: 'Micronesia' },
  { value: 'md', label: 'Moldova' },
  { value: 'mc', label: 'Monaco' },
  { value: 'mn', label: 'Mongolia' },
  { value: 'me', label: 'Montenegro' },
  { value: 'ma', label: 'Morocco' },
  { value: 'mz', label: 'Mozambique' },
  { value: 'mm', label: 'Myanmar' },
  { value: 'na', label: 'Namibia' },
  { value: 'nr', label: 'Nauru' },
  { value: 'np', label: 'Nepal' },
  { value: 'nl', label: 'Netherlands' },
  { value: 'nz', label: 'New Zealand' },
  { value: 'ni', label: 'Nicaragua' },
  { value: 'ne', label: 'Niger' },
  { value: 'ng', label: 'Nigeria' },
  { value: 'no', label: 'Norway' },
  { value: 'om', label: 'Oman' },
  { value: 'pk', label: 'Pakistan' },
  { value: 'pw', label: 'Palau' },
  { value: 'pa', label: 'Panama' },
  { value: 'pg', label: 'Papua New Guinea' },
  { value: 'py', label: 'Paraguay' },
  { value: 'pe', label: 'Peru' },
  { value: 'ph', label: 'Philippines' },
  { value: 'pl', label: 'Poland' },
  { value: 'pt', label: 'Portugal' },
  { value: 'qa', label: 'Qatar' },
  { value: 'ro', label: 'Romania' },
  { value: 'ru', label: 'Russia' },
  { value: 'rw', label: 'Rwanda' },
  { value: 'kn', label: 'Saint Kitts and Nevis' },
  { value: 'lc', label: 'Saint Lucia' },
  { value: 'vc', label: 'Saint Vincent and the Grenadines' },
  { value: 'ws', label: 'Samoa' },
  { value: 'sm', label: 'San Marino' },
  { value: 'st', label: 'Sao Tome and Principe' },
  { value: 'sa', label: 'Saudi Arabia' },
  { value: 'sn', label: 'Senegal' },
  { value: 'rs', label: 'Serbia' },
  { value: 'sc', label: 'Seychelles' },
  { value: 'sl', label: 'Sierra Leone' },
  { value: 'sg', label: 'Singapore' },
  { value: 'sk', label: 'Slovakia' },
  { value: 'si', label: 'Slovenia' },
  { value: 'sb', label: 'Solomon Islands' },
  { value: 'so', label: 'Somalia' },
  { value: 'za', label: 'South Africa' },
  { value: 'es', label: 'Spain' },
  { value: 'lk', label: 'Sri Lanka' },
  { value: 'sd', label: 'Sudan' },
  { value: 'sr', label: 'Suriname' },
  { value: 'sz', label: 'Eswatini' },
  { value: 'se', label: 'Sweden' },
  { value: 'ch', label: 'Switzerland' },
  { value: 'sy', label: 'Syria' },
  { value: 'tw', label: 'Taiwan' },
  { value: 'tj', label: 'Tajikistan' },
  { value: 'tz', label: 'Tanzania' },
  { value: 'th', label: 'Thailand' },
  { value: 'tg', label: 'Togo' },
  { value: 'to', label: 'Tonga' },
  { value: 'tt', label: 'Trinidad and Tobago' },
  { value: 'tn', label: 'Tunisia' },
  { value: 'tr', label: 'Turkey' },
  { value: 'tm', label: 'Turkmenistan' },
  { value: 'tv', label: 'Tuvalu' },
  { value: 'ug', label: 'Uganda' },
  { value: 'ua', label: 'Ukraine' },
  { value: 'ae', label: 'United Arab Emirates' },
  { value: 'gb', label: 'United Kingdom' },
  { value: 'us', label: 'United States' },
  { value: 'uy', label: 'Uruguay' },
  { value: 'uz', label: 'Uzbekistan' },
  { value: 'vu', label: 'Vanuatu' },
  { value: 'va', label: 'Vatican City' },
  { value: 've', label: 'Venezuela' },
  { value: 'vn', label: 'Vietnam' },
  { value: 'ye', label: 'Yemen' },
  { value: 'zm', label: 'Zambia' },
  { value: 'zw', label: 'Zimbabwe' },
];

export const countryOptionsRU = [
  { value: 'af', label: 'Афганистан' },
  { value: 'al', label: 'Албания' },
  { value: 'dz', label: 'Алжир' },
  { value: 'ad', label: 'Андорра' },
  { value: 'ao', label: 'Ангола' },
  { value: 'ag', label: 'Антигуа и Барбуда' },
  { value: 'ar', label: 'Аргентина' },
  { value: 'am', label: 'Армения' },
  { value: 'au', label: 'Австралия' },
  { value: 'at', label: 'Австрия' },
  { value: 'az', label: 'Азербайджан' },
  { value: 'bs', label: 'Багамы' },
  { value: 'bh', label: 'Бахрейн' },
  { value: 'bd', label: 'Бангладеш' },
  { value: 'bb', label: 'Барбадос' },
  { value: 'by', label: 'Беларусь' },
  { value: 'be', label: 'Бельгия' },
  { value: 'bz', label: 'Белиз' },
  { value: 'bj', label: 'Бенин' },
  { value: 'bt', label: 'Бутан' },
  { value: 'bo', label: 'Боливия' },
  { value: 'ba', label: 'Босния и Герцеговина' },
  { value: 'bw', label: 'Ботсвана' },
  { value: 'br', label: 'Бразилия' },
  { value: 'bn', label: 'Бруней' },
  { value: 'bg', label: 'Болгария' },
  { value: 'bf', label: 'Буркина-Фасо' },
  { value: 'bi', label: 'Бурунди' },
  { value: 'kh', label: 'Камбоджа' },
  { value: 'cm', label: 'Камерун' },
  { value: 'ca', label: 'Канада' },
  { value: 'cv', label: 'Кабо-Верде' },
  { value: 'cf', label: 'Центральноафриканская Республика' },
  { value: 'td', label: 'Чад' },
  { value: 'cl', label: 'Чили' },
  { value: 'cn', label: 'Китай' },
  { value: 'co', label: 'Колумбия' },
  { value: 'km', label: 'Коморы' },
  { value: 'cg', label: 'Конго' },
  { value: 'cr', label: 'Коста-Рика' },
  { value: 'hr', label: 'Хорватия' },
  { value: 'cu', label: 'Куба' },
  { value: 'cy', label: 'Кипр' },
  { value: 'cz', label: 'Чехия' },
  { value: 'cd', label: 'Демократическая Республика Конго' },
  { value: 'dk', label: 'Дания' },
  { value: 'dj', label: 'Джибути' },
  { value: 'dm', label: 'Доминика' },
  { value: 'do', label: 'Доминиканская Республика' },
  { value: 'tl', label: 'Восточный Тимор' },
  { value: 'ec', label: 'Эквадор' },
  { value: 'eg', label: 'Египет' },
  { value: 'sv', label: 'Сальвадор' },
  { value: 'gq', label: 'Экваториальная Гвинея' },
  { value: 'er', label: 'Эритрея' },
  { value: 'ee', label: 'Эстония' },
  { value: 'et', label: 'Эфиопия' },
  { value: 'fj', label: 'Фиджи' },
  { value: 'fi', label: 'Финляндия' },
  { value: 'fr', label: 'Франция' },
  { value: 'ga', label: 'Габон' },
  { value: 'gm', label: 'Гамбия' },
  { value: 'ge', label: 'Грузия' },
  { value: 'de', label: 'Германия' },
  { value: 'gh', label: 'Гана' },
  { value: 'gr', label: 'Греция' },
  { value: 'gd', label: 'Гренада' },
  { value: 'gt', label: 'Гватемала' },
  { value: 'gn', label: 'Гвинея' },
  { value: 'gw', label: 'Гвинея-Бисау' },
  { value: 'gy', label: 'Гайана' },
  { value: 'ht', label: 'Гаити' },
  { value: 'hn', label: 'Гондурас' },
  { value: 'hu', label: 'Венгрия' },
  { value: 'is', label: 'Исландия' },
  { value: 'in', label: 'Индия' },
  { value: 'id', label: 'Индонезия' },
  { value: 'ir', label: 'Иран' },
  { value: 'iq', label: 'Ирак' },
  { value: 'ie', label: 'Ирландия' },
  { value: 'il', label: 'Израиль' },
  { value: 'it', label: 'Италия' },
  { value: 'ci', label: 'Кот-д’Ивуар' },
  { value: 'jm', label: 'Ямайка' },
  { value: 'jp', label: 'Япония' },
  { value: 'jo', label: 'Иордания' },
  { value: 'kz', label: 'Казахстан' },
  { value: 'ke', label: 'Кения' },
  { value: 'ki', label: 'Кирибати' },
  { value: 'kp', label: 'Северная Корея' },
  { value: 'kr', label: 'Южная Корея' },
  { value: 'kw', label: 'Кувейт' },
  { value: 'kg', label: 'Киргизия' },
  { value: 'la', label: 'Лаос' },
  { value: 'lv', label: 'Латвия' },
  { value: 'lb', label: 'Ливан' },
  { value: 'ls', label: 'Лесото' },
  { value: 'lr', label: 'Либерия' },
  { value: 'ly', label: 'Ливия' },
  { value: 'li', label: 'Лихтенштейн' },
  { value: 'lt', label: 'Литва' },
  { value: 'lu', label: 'Люксембург' },
  { value: 'mk', label: 'Северная Македония' },
  { value: 'mg', label: 'Мадагаскар' },
  { value: 'mw', label: 'Малави' },
  { value: 'my', label: 'Малайзия' },
  { value: 'mv', label: 'Мальдивы' },
  { value: 'ml', label: 'Мали' },
  { value: 'mt', label: 'Мальта' },
  { value: 'mh', label: 'Маршалловы Острова' },
  { value: 'mr', label: 'Мавритания' },
  { value: 'mu', label: 'Маврикий' },
  { value: 'mx', label: 'Мексика' },
  { value: 'fm', label: 'Микронезия' },
  { value: 'md', label: 'Молдова' },
  { value: 'mc', label: 'Монако' },
  { value: 'mn', label: 'Монголия' },
  { value: 'me', label: 'Черногория' },
  { value: 'ma', label: 'Марокко' },
  { value: 'mz', label: 'Мозамбик' },
  { value: 'mm', label: 'Мьянма' },
  { value: 'na', label: 'Намибия' },
  { value: 'nr', label: 'Науру' },
  { value: 'np', label: 'Непал' },
  { value: 'nl', label: 'Нидерланды' },
  { value: 'nz', label: 'Новая Зеландия' },
  { value: 'ni', label: 'Никарагуа' },
  { value: 'ne', label: 'Нигер' },
  { value: 'ng', label: 'Нигерия' },
  { value: 'no', label: 'Норвегия' },
  { value: 'om', label: 'Оман' },
  { value: 'pk', label: 'Пакистан' },
  { value: 'pw', label: 'Палау' },
  { value: 'pa', label: 'Панама' },
  { value: 'pg', label: 'Папуа – Новая Гвинея' },
  { value: 'py', label: 'Парагвай' },
  { value: 'pe', label: 'Перу' },
  { value: 'ph', label: 'Филиппины' },
  { value: 'pl', label: 'Польша' },
  { value: 'pt', label: 'Португалия' },
  { value: 'qa', label: 'Катар' },
  { value: 'ro', label: 'Румыния' },
  { value: 'ru', label: 'Россия' },
  { value: 'rw', label: 'Руанда' },
  { value: 'kn', label: 'Сент-Китс и Невис' },
  { value: 'lc', label: 'Сент-Люсия' },
  { value: 'vc', label: 'Сент-Винсент и Гренадины' },
  { value: 'ws', label: 'Самоа' },
  { value: 'sm', label: 'Сан-Марино' },
  { value: 'st', label: 'Сан-Томе и Принсипи' },
  { value: 'sa', label: 'Саудовская Аравия' },
  { value: 'sn', label: 'Сенегал' },
  { value: 'rs', label: 'Сербия' },
  { value: 'sc', label: 'Сейшельские Острова' },
  { value: 'sl', label: 'Сьерра-Леоне' },
  { value: 'sg', label: 'Сингапур' },
  { value: 'sk', label: 'Словакия' },
  { value: 'si', label: 'Словения' },
  { value: 'sb', label: 'Соломоновы Острова' },
  { value: 'so', label: 'Сомали' },
  { value: 'za', label: 'Южно-Африканская Республика' },
  { value: 'es', label: 'Испания' },
  { value: 'lk', label: 'Шри-Ланка' },
  { value: 'sd', label: 'Судан' },
  { value: 'sr', label: 'Суринам' },
  { value: 'sz', label: 'Эсватини' },
  { value: 'se', label: 'Швеция' },
  { value: 'ch', label: 'Швейцария' },
  { value: 'sy', label: 'Сирия' },
  { value: 'tw', label: 'Тайвань' },
  { value: 'tj', label: 'Таджикистан' },
  { value: 'tz', label: 'Танзания' },
  { value: 'th', label: 'Таиланд' },
  { value: 'tg', label: 'Того' },
  { value: 'to', label: 'Тонга' },
  { value: 'tt', label: 'Тринидад и Тобаго' },
  { value: 'tn', label: 'Тунис' },
  { value: 'tr', label: 'Турция' },
  { value: 'tm', label: 'Туркмения' },
  { value: 'tv', label: 'Тувалу' },
  { value: 'ug', label: 'Уганда' },
  { value: 'ua', label: 'Украина' },
  { value: 'ae', label: 'Объединённые Арабские Эмираты' },
  { value: 'gb', label: 'Соединённое Королевство' },
  { value: 'us', label: 'Соединённые Штаты' },
  { value: 'uy', label: 'Уругвай' },
  { value: 'uz', label: 'Узбекистан' },
  { value: 'vu', label: 'Вануату' },
  { value: 'va', label: 'Ватикан' },
  { value: 've', label: 'Венесуэла' },
  { value: 'vn', label: 'Вьетнам' },
  { value: 'ye', label: 'Йемен' },
  { value: 'zm', label: 'Замбия' },
  { value: 'zw', label: 'Зимбабве' },
];

export const countryOptionsFR = [
  { value: 'af', label: 'Afghanistan' },
  { value: 'al', label: 'Albanie' },
  { value: 'dz', label: 'Algérie' },
  { value: 'ad', label: 'Andorre' },
  { value: 'ao', label: 'Angola' },
  { value: 'ag', label: 'Antigua-et-Barbuda' },
  { value: 'ar', label: 'Argentine' },
  { value: 'am', label: 'Arménie' },
  { value: 'au', label: 'Australie' },
  { value: 'at', label: 'Autriche' },
  { value: 'az', label: 'Azerbaïdjan' },
  { value: 'bs', label: 'Bahamas' },
  { value: 'bh', label: 'Bahreïn' },
  { value: 'bd', label: 'Bangladesh' },
  { value: 'bb', label: 'Barbade' },
  { value: 'by', label: 'Biélorussie' },
  { value: 'be', label: 'Belgique' },
  { value: 'bz', label: 'Belize' },
  { value: 'bj', label: 'Bénin' },
  { value: 'bt', label: 'Bhoutan' },
  { value: 'bo', label: 'Bolivie' },
  { value: 'ba', label: 'Bosnie-Herzégovine' },
  { value: 'bw', label: 'Botswana' },
  { value: 'br', label: 'Brésil' },
  { value: 'bn', label: 'Brunei' },
  { value: 'bg', label: 'Bulgarie' },
  { value: 'bf', label: 'Burkina Faso' },
  { value: 'bi', label: 'Burundi' },
  { value: 'kh', label: 'Cambodge' },
  { value: 'cm', label: 'Cameroun' },
  { value: 'ca', label: 'Canada' },
  { value: 'cv', label: 'Cap-Vert' },
  { value: 'cf', label: 'République Centrafricaine' },
  { value: 'td', label: 'Tchad' },
  { value: 'cl', label: 'Chili' },
  { value: 'cn', label: 'Chine' },
  { value: 'co', label: 'Colombie' },
  { value: 'km', label: 'Comores' },
  { value: 'cg', label: 'Congo' },
  { value: 'cr', label: 'Costa Rica' },
  { value: 'hr', label: 'Croatie' },
  { value: 'cu', label: 'Cuba' },
  { value: 'cy', label: 'Chypre' },
  { value: 'cz', label: 'Tchéquie' },
  { value: 'cd', label: 'République Démocratique du Congo' },
  { value: 'dk', label: 'Danemark' },
  { value: 'dj', label: 'Djibouti' },
  { value: 'dm', label: 'Dominique' },
  { value: 'do', label: 'République Dominicaine' },
  { value: 'tl', label: 'Timor oriental' },
  { value: 'ec', label: 'Équateur' },
  { value: 'eg', label: 'Égypte' },
  { value: 'sv', label: 'Salvador' },
  { value: 'gq', label: 'Guinée équatoriale' },
  { value: 'er', label: 'Érythrée' },
  { value: 'ee', label: 'Estonie' },
  { value: 'et', label: 'Éthiopie' },
  { value: 'fj', label: 'Fidji' },
  { value: 'fi', label: 'Finlande' },
  { value: 'fr', label: 'France' },
  { value: 'ga', label: 'Gabon' },
  { value: 'gm', label: 'Gambie' },
  { value: 'ge', label: 'Géorgie' },
  { value: 'de', label: 'Allemagne' },
  { value: 'gh', label: 'Ghana' },
  { value: 'gr', label: 'Grèce' },
  { value: 'gd', label: 'Grenade' },
  { value: 'gt', label: 'Guatemala' },
  { value: 'gn', label: 'Guinée' },
  { value: 'gw', label: 'Guinée-Bissau' },
  { value: 'gy', label: 'Guyana' },
  { value: 'ht', label: 'Haïti' },
  { value: 'hn', label: 'Honduras' },
  { value: 'hu', label: 'Hongrie' },
  { value: 'is', label: 'Islande' },
  { value: 'in', label: 'Inde' },
  { value: 'id', label: 'Indonésie' },
  { value: 'ir', label: 'Iran' },
  { value: 'iq', label: 'Irak' },
  { value: 'ie', label: 'Irlande' },
  { value: 'il', label: 'Israël' },
  { value: 'it', label: 'Italie' },
  { value: 'ci', label: 'Côte d’Ivoire' },
  { value: 'jm', label: 'Jamaïque' },
  { value: 'jp', label: 'Japon' },
  { value: 'jo', label: 'Jordanie' },
  { value: 'kz', label: 'Kazakhstan' },
  { value: 'ke', label: 'Kenya' },
  { value: 'ki', label: 'Kiribati' },
  { value: 'kp', label: 'Corée du Nord' },
  { value: 'kr', label: 'Corée du Sud' },
  { value: 'kw', label: 'Koweït' },
  { value: 'kg', label: 'Kirghizistan' },
  { value: 'la', label: 'Laos' },
  { value: 'lv', label: 'Lettonie' },
  { value: 'lb', label: 'Liban' },
  { value: 'ls', label: 'Lesotho' },
  { value: 'lr', label: 'Libéria' },
  { value: 'ly', label: 'Libye' },
  { value: 'li', label: 'Liechtenstein' },
  { value: 'lt', label: 'Lituanie' },
  { value: 'lu', label: 'Luxembourg' },
  { value: 'mk', label: 'Macédoine du Nord' },
  { value: 'mg', label: 'Madagascar' },
  { value: 'mw', label: 'Malawi' },
  { value: 'my', label: 'Malaisie' },
  { value: 'mv', label: 'Maldives' },
  { value: 'ml', label: 'Mali' },
  { value: 'mt', label: 'Malte' },
  { value: 'mh', label: 'Îles Marshall' },
  { value: 'mr', label: 'Mauritanie' },
  { value: 'mu', label: 'Maurice' },
  { value: 'mx', label: 'Mexique' },
  { value: 'fm', label: 'Micronésie' },
  { value: 'md', label: 'Moldavie' },
  { value: 'mc', label: 'Monaco' },
  { value: 'mn', label: 'Mongolie' },
  { value: 'me', label: 'Monténégro' },
  { value: 'ma', label: 'Maroc' },
  { value: 'mz', label: 'Mozambique' },
  { value: 'mm', label: 'Myanmar' },
  { value: 'na', label: 'Namibie' },
  { value: 'nr', label: 'Nauru' },
  { value: 'np', label: 'Népal' },
  { value: 'nl', label: 'Pays-Bas' },
  { value: 'nz', label: 'Nouvelle-Zélande' },
  { value: 'ni', label: 'Nicaragua' },
  { value: 'ne', label: 'Niger' },
  { value: 'ng', label: 'Nigéria' },
  { value: 'no', label: 'Norvège' },
  { value: 'om', label: 'Oman' },
  { value: 'pk', label: 'Pakistan' },
  { value: 'pw', label: 'Palaos' },
  { value: 'pa', label: 'Panama' },
  { value: 'pg', label: 'Papouasie-Nouvelle-Guinée' },
  { value: 'py', label: 'Paraguay' },
  { value: 'pe', label: 'Pérou' },
  { value: 'ph', label: 'Philippines' },
  { value: 'pl', label: 'Pologne' },
  { value: 'pt', label: 'Portugal' },
  { value: 'qa', label: 'Qatar' },
  { value: 'ro', label: 'Roumanie' },
  { value: 'ru', label: 'Russie' },
  { value: 'rw', label: 'Rwanda' },
  { value: 'kn', label: 'Saint-Christophe-et-Niévès' },
  { value: 'lc', label: 'Sainte-Lucie' },
  { value: 'vc', label: 'Saint-Vincent-et-les-Grenadines' },
  { value: 'ws', label: 'Samoa' },
  { value: 'sm', label: 'Saint-Marin' },
  { value: 'st', label: 'Sao Tomé-et-Principe' },
  { value: 'sa', label: 'Arabie Saoudite' },
  { value: 'sn', label: 'Sénégal' },
  { value: 'rs', label: 'Serbie' },
  { value: 'sc', label: 'Seychelles' },
  { value: 'sl', label: 'Sierra Leone' },
  { value: 'sg', label: 'Singapour' },
  { value: 'sk', label: 'Slovaquie' },
  { value: 'si', label: 'Slovénie' },
  { value: 'sb', label: 'Îles Salomon' },
  { value: 'so', label: 'Somalie' },
  { value: 'za', label: 'Afrique du Sud' },
  { value: 'es', label: 'Espagne' },
  { value: 'lk', label: 'Sri Lanka' },
  { value: 'sd', label: 'Soudan' },
  { value: 'sr', label: 'Suriname' },
  { value: 'sz', label: 'Eswatini' },
  { value: 'se', label: 'Suède' },
  { value: 'ch', label: 'Suisse' },
  { value: 'sy', label: 'Syrie' },
  { value: 'tw', label: 'Taïwan' },
  { value: 'tj', label: 'Tadjikistan' },
  { value: 'tz', label: 'Tanzanie' },
  { value: 'th', label: 'Thaïlande' },
  { value: 'tg', label: 'Togo' },
  { value: 'to', label: 'Tonga' },
  { value: 'tt', label: 'Trinité-et-Tobago' },
  { value: 'tn', label: 'Tunisie' },
  { value: 'tr', label: 'Turquie' },
  { value: 'tm', label: 'Turkménistan' },
  { value: 'tv', label: 'Tuvalu' },
  { value: 'ug', label: 'Ouganda' },
  { value: 'ua', label: 'Ukraine' },
  { value: 'ae', label: 'Émirats Arabes Unis' },
  { value: 'gb', label: 'Royaume-Uni' },
  { value: 'us', label: 'États-Unis' },
  { value: 'uy', label: 'Uruguay' },
  { value: 'uz', label: 'Ouzbékistan' },
  { value: 'vu', label: 'Vanuatu' },
  { value: 'va', label: 'Vatican' },
  { value: 've', label: 'Venezuela' },
  { value: 'vn', label: 'Viêt Nam' },
  { value: 'ye', label: 'Yémen' },
  { value: 'zm', label: 'Zambie' },
  { value: 'zw', label: 'Zimbabwe' },
];
